### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by 23Skidoo** [erikd/vector-algorithms#14]
Would be nice if I didn't have to go to GitHub commit log to find out what's new in a new major version.

**Comment by cartazio** [comment]
@erikd PLEASE :)

**Comment by nh2** [comment]
Done since commit https://github.com/erikd/vector-algorithms/commit/10a18dcc3f2b2928cf90bdefc790b1a5dec1740f#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

**Comment by erikd** [comment]
Closing. Thanks @nh2 for noticing.
