### ISSUE TITLE
Overflow bugs

### ISSUE THREAD

**Issue by dolio** [erikd/vector-algorithms#2]
This was reported to me via e-mail by Chai T. Rex:

I've found a small bug in three modules.

Midpoint calculation potential overflows exist. In particular, if (u + l) is large enough to overflow to a negative Int, both (u + l) `div` 2 and (u + l) `shiftR` 1 will preserve the negative sign. A Google AI Blog post gives a solution for languages like Haskell without logical right shifts:

    mid = ((unsigned int)low + (unsigned int)high)) >> 1;

In Haskell, this is:

    fromIntegral ((fromIntegral u + fromIntegral l) `shiftR` 1 :: Word) :: Int

A demonstration of the proposed replacement's correctness and the current versions' incorrectness by getting the midpoint of maxBound - 2 and maxBound, which should be maxBound - 1:

    GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
    Prelude> :m + Data.Bits Data.Word
    Prelude Data.Bits Data.Word> let { f :: Int -> Int -> Int; f l u = fromIntegral ((fromIntegral u + fromIntegral l) `shiftR` 1 :: Word) :: Int }
    Prelude Data.Bits Data.Word> let { g :: Int -> Int -> Int; g l u = (u + l) `div` 2 }
    Prelude Data.Bits Data.Word> let { h :: Int -> Int -> Int; h l u = (u + l) `shiftR` 1 }
    Prelude Data.Bits Data.Word> maxBound - 1 :: Int
    9223372036854775806
    Prelude Data.Bits Data.Word> f (maxBound - 2) maxBound
    9223372036854775806
    Prelude Data.Bits Data.Word> g (maxBound - 2) maxBound
    -2
    Prelude Data.Bits Data.Word> h (maxBound - 2) maxBound
    -2

The buggy lines in particular:

    $ fgrep -n '(u + l)' src/Data/Vector/Algorithms/*
    src/Data/Vector/Algorithms/Intro.hs:109:  c   = (u + l) `div` 2
    src/Data/Vector/Algorithms/Intro.hs:158:  where c = (u + l) `div` 2
    src/Data/Vector/Algorithms/Intro.hs:210:  where c = (u + l) `div` 2
    src/Data/Vector/Algorithms/Merge.hs:63:        mid = (u + l) `shiftR` 1
    src/Data/Vector/Algorithms/Search.hs:73:  where k = (u + l) `shiftR` 1
    src/Data/Vector/Algorithms/Search.hs:139:  where k = (u + l) `shiftR` 1

**Comment by dolio** [comment]
Here's the referenced blog post:

https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html

**Comment by erikd** [comment]
I'm a little skeptical of the practical danger of this issue, at least on 64 bits systems.

This potential overflow can only be hit if the two values add up something larger than `maxBound ::Int`. At least 64 bit systems this is way more memory that any currently available 64 bit CPU has address space. Most modern CPUs only have 48 bits of virtual address space. Admittedly, on 32 bit systems, with 4G of RAM this is a potential problem.

**Comment by erikd** [comment]
Turns out fixing it was way easier than I first thought. Solution was as easy as defining:
```
midPoint :: Int -> Int -> Int
midPoint a b =
  toInt $ (toWord a + toWord b) `div` 2
  where
    toWord :: Int -> Word
    toWord = fromIntegral

    toInt :: Word -> Int
    toInt = fromIntegral
{-# INLINE midPoint #-}
```
and replacing the existing expression with this new one.
