### ISSUE TITLE
What are the  breaking changes in vector-algorithms-0.9.0.1 ?

### ISSUE THREAD

**Issue by phadej** [erikd/vector-algorithms#41]

**Comment by erikd** [comment]
Ah, the changes weren't breaking changes, just added functionality in commits 62c5987962e5621e7b63e0d088c5f7326c8ca7f0 and a8b985c16ae9d6560376f57eb7a9a175b4e3ea78 .

Maybe the version should have just been `0.8.1.0` instead.
