### ISSUE TITLE
Recent versions fail to build on GHC 7.6.3

### ISSUE THREAD

**Issue by adamgundry** [erikd/vector-algorithms#5]
See https://matrix.hackage.haskell.org/package/vector-algorithms#GHC-7.6/vector-algorithms-0.7.0.3. It seems that 0.7.0.2 and later use `Data.Proxy`, which was not exported in GHC 7.6.3. I guess adding a dependency on `tagged` is the simplest fix, as it will (re)export `Data.Proxy` as needed.

**Comment by erikd** [comment]
Fixed in 0.7.0.4.

**Comment by adamgundry** [comment]
Thanks for the quick fix! My CI script is happy again. :smile:
