### ISSUE TITLE
Breaking changes without PVP bump

### ISSUE THREAD

**Issue by HuwCampbell** [erikd/vector-algorithms#9]
Just a heads up that in 0.7.0.2 the definition of the `Data.Vector.Algorithms.AmericanFlag.Lexicographic` class changed in breaking manner.

**Comment by hvr** [comment]
@erikd my recommended course of action:

Given the 0.7.0.1 release dates back to 2015, whereas 0.7.0.2 was only released recently last month
and that the `Lexicographic` class was significantly changed in 0.7.0.2 (but the required version bump was inadvertently missed):

- blacklist/deprecate the vector-algorithms release 0.7.0.2 through 0.7.0.4, and
- re-release the latest 0.7.0.4 as 0.8.0.0

**Comment by erikd** [comment]
Have released 0.8.0.0 and deprecated the required versions.
